import globals from "globals";
import nextPlugin from "@next/eslint-plugin-next";
import reactPlugin from "eslint-plugin-react";
import hooksPlugin from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";
import baseConfig from "./base.mjs";

/** ESLint flat config for the Next.js app. */
export default [
  ...baseConfig,
  // Generated by Next; uses triple-slash references that lint rules flag.
  { ignores: ["next-env.d.ts"] },
  reactPlugin.configs.flat.recommended,
  reactPlugin.configs.flat["jsx-runtime"],
  hooksPlugin.configs.flat["recommended-latest"],
  nextPlugin.configs.recommended,
  nextPlugin.configs["core-web-vitals"],
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    settings: { react: { version: "19.0" } },
    rules: {
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",
    },
  },
  // Keep last: turn off stylistic rules that would fight Prettier.
  prettier,
];
